### ISSUE TITLE
have you handled the proguard issue?

### ISSUE THREAD

**Issue by yantao2hao** [KagayamaKaede/ShadowsocksRDroid#10]

**Comment by KagayamaKaede** [comment]
On my device(android 5.1.1), It worked fine. If you have any advice, thanks for share.

**Comment by yantao2hao** [comment]
-keep class com.proxy.shadowsocksr.** { *; }
All the classes are not proguard,but if remove this,it don't work.
i have device from 4.2 to 4.4,they all do not work.

**Comment by KagayamaKaede** [comment]
I am not familiar with proguard, I still learning it , so, sorry, I do not have any solutions yet.

**Comment by yantao2hao** [comment]
Thank you so much

**Comment by KagayamaKaede** [comment]
@yantao2hao 
hi,I research some proguard knowledge.
I use public fields in Serializable class. so, add below to keep 2 class:
```proguard
-keep class com.proxy.shadowsocksr.items.SSRProfile { *; }
-keep class com.proxy.shadowsocksr.items.GlobalProfile { *; }
```
Then, issue should be resolved. Later I will push the latest code。
