### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by MrSong0607** [KagayamaKaede/ShadowsocksRDroid#11]
系统安卓5.0.4，手机是华为荣耀7

**Comment by KagayamaKaede** [comment]
@MrSong0607 有无安装之前的版本？如果有，尝试清空App的数据。

**Comment by MrSong0607** [comment]
@KagayamaKaede 可以打开了，但是用不了，无法访问网络，协议auth simple，混淆方法random head

**Comment by KagayamaKaede** [comment]
random head 暂未实现，目前http_simple可用，协议auth和verify_simple可用，但不稳定

**Comment by MrSong0607** [comment]
@KagayamaKaede 好的
