### ISSUE TITLE
能否支持更多加密方式

### ISSUE THREAD

**Issue by icesshadows** [KagayamaKaede/ShadowsocksRDroid#17]
现有的加密方式过少，部分常用的加密方式不支持，实在不便，望开发者予以考虑。

**Comment by KagayamaKaede** [comment]
我现在主要跟随ssr-c#的实现去做。你需要额外添加什么加密方式，我在下个版本加入。因为我是用java实现，代码过多会导致apk体积膨胀的厉害。

**Comment by icesshadows** [comment]
能否考虑一下在下一个版本支持rc4-md5？

**Comment by KagayamaKaede** [comment]
这个原版ss都不支持了吧，rc4-md5已经是公认的不安全了

**Comment by mikelei8291** [comment]
原版和ssr都还在支持，虽然安全性比 `aes-256-cfb` 差，但是对某些移动设备还是会好一点，但是现在的建议其实是用性能更好的 `chacha20`

**Comment by KagayamaKaede** [comment]
电脑aes，手机chacha，我觉得已经足够了。
@icesshadows 下个版本我加上rc4

**Comment by binaijing** [comment]
我用的这个shadowX网址在用rc4-md5加密方式。

**Comment by KagayamaKaede** [comment]
@icesshadows @binaijing 最新版已经添加rc4-md5
