### ISSUE TITLE
在修改自定义端口时有闪退现象

### ISSUE THREAD

**Issue by simonsmh** [KagayamaKaede/ShadowsocksRDroid#3]
在修改自定义端口时有闪退现象，希望修复，谢谢！

**Comment by falseen** [comment]
我这边修改端口直接报错

**Comment by KagayamaKaede** [comment]
问题已经修复，感谢反馈。
原因在于我修改配置存储机制后没有做手动添加服务器测试（习惯直接用二维码添加了）。导致读取端口配置信息数据类型不匹配。
新版本已经push。

**Comment by simonsmh** [comment]
感谢修复！
