### ISSUE TITLE
若不勾选UDP转发选项则无法访问网络

### ISSUE THREAD

**Issue by iKirby** [KagayamaKaede/ShadowsocksRDroid#4]
用SSAndroid时候我一直没有勾选，发现这个版本默认勾选了于是就去除勾选，结果发现无法打开网页。勾上后重连就恢复正常，但是路由功能好像不起作用了。我设置的绕过局域网和列表，发现访问国内站点依然会通过代理进行连接。

**Comment by KagayamaKaede** [comment]
感谢反馈，问题已经修复。

**Comment by yantaodehaoma** [comment]
sodium/version.h  missing!!

**Comment by KagayamaKaede** [comment]
@yantaodehaoma Thank you. I added.
Very strange, In shadowsocks-android repo, This file is ignored.

**Comment by iKirby** [comment]
现在不选择UDP转发，已经正常了。但是路由功能还是不行，访问国内站点还是会走代理

**Comment by KagayamaKaede** [comment]
@iKirby 请问你使用原版影梭时，路由选择“绕过局域网及中国大陆地址”时，用百度搜索IP时，显示的是你本地的IP而不是服务器IP？

**Comment by iKirby** [comment]
@KagayamaKaede 是的，显示是我的本地IP，不是服务器IP

**Comment by KagayamaKaede** [comment]
奇怪了，我用原版时仍然显示我的服务器IP。

就我个人来看，不建议绕过大陆地址，因为某些情况下如果同一会话访问同一站点有2个IP的流量会很可疑。我个人使用的2个浏览器，一个全翻，一个上国内站。

我会继续查找问题所在，再次感谢反馈。

**Comment by KagayamaKaede** [comment]
@iKirby 这个issue已经解决，新的版本已经放出，感谢测试：[SSRv1.0.4Beta](https://github.com/KagayamaKaede/ShadowsocksRDroid/releases/tag/v1.0.4Beta)

**Comment by iKirby** [comment]
@KagayamaKaede 刚才下载测试了。貌似还是有问题...路由选择绕过局域网和列表，勾选UDP转发的情况下，可以打开google，但无法打开百度；不勾选UDP转发的情况下，任何页面都打不开。我手机系统升级到了Android 6.0，不知道是不是系统的问题，不过Play商店那个原版的使用正常。4G和WiFi都是这样。

**Comment by KagayamaKaede** [comment]
@iKirby 仔细调试了下，发现一些潜在的异常存在，导致再次连接会出现无法连接的问题。

这次一定了修复了问题。感谢测试：[SSRv1.0.5Beta](https://github.com/KagayamaKaede/ShadowsocksRDroid/releases/tag/v1.0.5Beta)

另外想确认一件事，你在使用原版时，选择```绕过局域网和列表```并勾选```UDP转发```，访问百度搜索IP时，显示的是本地IP还是远程IP？

**Comment by iKirby** [comment]
@KagayamaKaede 刚看到邮件提醒，测试了，在不勾选UDP转发的情况下，百度IP显示的是本地IP。在勾选的情况下，无法打开百度，可以打开Google等墙外页面。原版勾选UDP转发时候，也是一样，打不开百度，可以打开墙外。

**Comment by KagayamaKaede** [comment]
如果问题解决，请关闭该issue，谢谢~
