### ISSUE TITLE
请问SSR协议可用吗?现在

### ISSUE THREAD

**Issue by shuiyind** [KagayamaKaede/ShadowsocksRDroid#5]
还有.我比较 蠢(NB),实在是不懂怎么编辑源码打包成程序.可否给一个现成的谢谢+_+ /一个 萌萌哒2货
 对了 我是 三星S5 移动版.安卓5.0 root了.能用吧+_+

**Comment by breakwa11** [comment]
目前还不能。。。协议还在完善中。。。

**Comment by shuiyind** [comment]
好的+_+

**Comment by KagayamaKaede** [comment]
@shuiyind 目前实现了第一个测试版本，如有时间可以去尝试，不过该版本存在不少问题。如果测试过程中发现问题，欢迎反馈。

**Comment by shuiyind** [comment]
不知道哪里下载.+_+不会打包...

在 2015年11月9日 下午8:43，KagayamaKaede <notifications@github.com>写道：

**Comment by shuiyind** [comment]
找到了

在 2015年11月10日 上午9:40，水银灯 <shuiyind@gmail.com>写道：
