### ISSUE TITLE
Is that possible to set the compatibility to android Ice Cream Sandwich (API level 14)?

### ISSUE THREAD

**Issue by yantaodehaoma** [KagayamaKaede/ShadowsocksRDroid#6]
API level 17 is a little too high!

**Comment by KagayamaKaede** [comment]
Yes, but not now, below api17 need process more questions and National Day holiday is over, my spare time fewer. so, this issue may take a long time to resolve.

**Comment by yantaodehaoma** [comment]
Is instagram bypassed?  Cannot get through instagram

**Comment by yantaodehaoma** [comment]
below api17 need process more questions,you mean the ui or daemon binary or vpnserver ?

**Comment by KagayamaKaede** [comment]
1. I haven't test VPNService below api17, may be not work, and I did not write NAT mode.
2. Below api17,DNS flush function need rewrite.

You want to instagram use proxy or not?

**Comment by yantaodehaoma** [comment]
To instagram use proxy,thanks

**Comment by KagayamaKaede** [comment]
@yantaodehaoma I try to install instagram and tested it, instagram can use proxy connected to the internet. Are you sure you checked it, or used a global mode, and other App worked?

**Comment by yantaodehaoma** [comment]
perhaps it's my router's fault,thank you very much!

**Comment by KagayamaKaede** [comment]
You are welcome.

**Comment by KagayamaKaede** [comment]
@yantaodehaoma I try compile compatibility api14.
You can try it:[SSRv1.0.6Beta](https://github.com/KagayamaKaede/ShadowsocksRDroid/releases/tag/v1.0.6Beta),Thanks for test.
