### ISSUE TITLE
ICMP报文好像不通了

### ISSUE THREAD

**Issue by yantaodehaoma** [KagayamaKaede/ShadowsocksRDroid#7]
不知道有没有人碰到过，打开vpn后，手机ping服务器超时，有好的解决方案吗？

**Comment by KagayamaKaede** [comment]
Socks代理是TCP代理（Socks5可以代理UDP），ICMP不基于TCP或UDP。

**Comment by yantaodehaoma** [comment]
谢谢，
既然没有影响这些报文，为什么打开ss，所有的ping都不通呢？

**Comment by KagayamaKaede** [comment]
你是不是开了全局代理，还是你用的终端软件被代理了？我这边测试开SSR，不代理终端软件，能够正常ping通。

**Comment by yantaodehaoma** [comment]
确实是开了全局代理，这个会影响ping吗？

**Comment by KagayamaKaede** [comment]
会，如果你有App依赖于ICMP，那么不要让他走代理。

**Comment by yantaodehaoma** [comment]
我是在adb里面ping，app没有依赖于ICMP的

**Comment by KagayamaKaede** [comment]
如果没有影响可以不用在意这个问题。

**Comment by yantaodehaoma** [comment]
想在不关闭vpn的前提下对服务器进行测速，但是ping不通

**Comment by KagayamaKaede** [comment]
通过下载测速，随便从商店下载一个比较大的App。ping不一定能正确反映你的网络体验速度。

**Comment by mikelei8291** [comment]
ping只能显示是否能连接，测速建议用OOKLA测速
speedtest.net

**Comment by yantaodehaoma** [comment]
谢谢，ping是为了找一个相对好点的server，一来测试连接，二来看看速度。

**Comment by KagayamaKaede** [comment]
@yantaodehaoma 如果问题解决，麻烦关闭issue，感谢！
