### ISSUE TITLE
请问本地端口应该如何配置？

### ISSUE THREAD

**Issue by yantaodehaoma** [KagayamaKaede/ShadowsocksRDroid#8]
public final static String defaultIP = "1.2.3.4";
    public final static String defaultMethod = "aes-256-cfb";
    public final static String defaultPassword = "cs7cysc6ts6cstcst";
    public final static int remotePort = 2333;
    public final static int localPort = 23333;

默认23333是不通的

**Comment by KagayamaKaede** [comment]
麻烦详细描述下你遇到的问题。
安卓上localPort一般不需要修改，如果VPN启动失败可以尝试修改localPort.

**Comment by KagayamaKaede** [comment]
@yantaodehaoma 如果issue解决，麻烦关闭issue，感谢！

**Comment by yantaodehaoma** [comment]
locaPort是否与Daemon命令的配置有关？ 比如下面命令的8163，那么在Const中是否改成8163？
        ShellUtil.runCmd((Consts.baseDir +
                "ss-tunnel -V -u -t 10 -b 127.0.0.1 -l 8163 -L 8.8.8.8:53 -c " +
                Consts.baseDir + "ss-tunnel-vpn.conf -f " + Consts.baseDir +
                "ss-tunnel-vpn.pid"));

**Comment by KagayamaKaede** [comment]
localPort是ss-local监听本地连接所使用的端口，它是写在ss-local-vpn.conf配置文件里的。
而-l 8163是给pdnsd连接做dns解析通道用的。
Consts里的localPort是手动新建服务器配置时所使用的默认值，这个值可以通过App的设置直接修改（虽然通常并不需要修改）

**Comment by yantaodehaoma** [comment]
thanks
